version: "3.8"
services:
  app:
    container_name: zaico_books_app
    build: ./docker/php
    volumes:
      - .:/var/www/html
  web:
    container_name: zaico_books_web
    image: nginx:1.18
    ports:
      - "8991:80"
    volumes:
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - .:/var/www/html
    depends_on:
      - app
  db:
    container_name: zaico_books_db
    build: ./docker/mysql
    volumes:
      - ./docker/db:/db
      